import{S as d,i as y}from"./assets/vendor-46aac873.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const o of r.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&n(o)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const h="https://pixabay.com/api/",c={key:"42034785-c436f003c310c5b5229f24b7b",q:"",image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:27},g=new d(".gallery a",{overlayOpacity:.7,captionsData:"alt",captionDelay:250}),b=document.querySelector(".gallery-form"),p=document.querySelector(".search-input"),u=document.querySelector(".gallery"),i=document.querySelector(".loader");b.addEventListener("submit",S);function S(s){if(s.preventDefault(),!p.value.trim()){l("Please fill in the search field");return}const t=s.currentTarget;L().then(a=>w(a)).catch(a=>l(`Something was wrong ${a}`)).finally(()=>{t.reset(),g.refresh()})}function L(){u.innerHTML="",i.style.display="inline-block",c.q=p.value.trim();const s=new URLSearchParams(c).toString();return fetch(`${h}?${s}`).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()})}function w(s){if(!s.total){l("Sorry, there are no images matching your search query. Please, try again!"),i.style.display="none";return}const t=s.hits.map(({largeImageURL:a,webformatURL:n,tags:e,likes:r,views:o,comments:f,downloads:m})=>`<li class="gallery-item">
          <a href="${a}">
            <img class="api-img" src="${n}" alt="${e}">
            <div class="img-desc">
            <p class="para">Likes: <span class="span"> <br/>${r}</span></p>
            <p class="para">Views: <span class="span"> <br/>${o}</span></p>
            <p class="para">Comments: <span class="span"> <br/>${f}</span></p>
            <p class="para">Downloads: <span class="span"> <br/>${m}</span></p>
            </div>
          </a>
        </li>`).join("");u.insertAdjacentHTML("afterbegin",t),i.style.display="none"}function l(s){y.show({position:"bottomCenter",title:"X",titleColor:"#fff",titleSize:"22px",message:s,backgroundColor:"#EF4040",messageColor:"#FAFAFB",messageSize:"16px",close:!1,closeOnClick:!0,closeOnEscape:!0})}
//# sourceMappingURL=commonHelpers.js.map
